"""Credentials, sessions and grants — the frontend's half of the trust model.

The relay verifies devices and grants but knows nothing about people. Everything
to do with users lives on this side: password hashing, the browser session, and
the signing of the short-lived grants the relay will accept.

Because the browser and this app share an origin, the session is a plain
``HttpOnly`` cookie — not a token in ``localStorage``, which any injected script
could read. The cookie carries the user's role so page guards do not have to hit
the database on every request; it is re-read from the database on login, so a
role change takes effect at the user's next sign-in.
"""

from __future__ import annotations

import logging
import secrets
from datetime import datetime, timedelta, timezone
from typing import Dict, Optional

from jose import JWTError, jwt
from passlib.context import CryptContext
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import ROLE_ADMIN, ROLE_OPERATOR, User, user as users

logger = logging.getLogger(__name__)

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
ALGORITHM = "HS256"

SESSION_COOKIE = "wdc_session"
VALID_SCOPES = {"terminal", "upload", "download"}

# bcrypt hash of "admin", so a fresh checkout runs. Override in production with
# ADMIN_PASSWORD_HASH, generated by `python -m tools.hash_password`.
DEV_ADMIN_HASH = "$2b$12$wfP4VFGOk31Wf5GCcic0Ge6fEA5/ud9tPHPah9IFGV9GIGI0bH6wK"

# Failed lookups should take as long as real ones, so response time does not
# reveal whether a username exists.
_DUMMY_HASH = pwd_context.hash("dummy-password")


def startup_warnings() -> None:
    if not settings.session_secret:
        logger.error("SESSION_SECRET is unset: sessions cannot be signed.")
    if not settings.relay_secret:
        logger.error(
            "RELAY_SECRET is unset: the relay will reject every grant. Set the "
            "same value here and in server/.env."
        )


def hash_password(password: str) -> str:
    return pwd_context.hash(password)


async def ensure_bootstrap_admin(session: AsyncSession) -> None:
    """Seed the first admin, only when there are no users at all.

    Deliberately not an upsert: once a real administrator exists, the environment
    variables stop mattering, so rotating ADMIN_PASSWORD_HASH cannot silently
    reset a password that has since been changed through the UI.
    """
    if list(await users.list_all(session)):
        return

    password_hash = settings.admin_password_hash or DEV_ADMIN_HASH
    await users.create(
        session,
        username=settings.admin_username,
        password_hash=password_hash,
        role=ROLE_ADMIN,
    )
    logger.warning(
        "seeded the initial administrator %r. Change its password before exposing "
        "this beyond your machine.", settings.admin_username
    )
    if password_hash == DEV_ADMIN_HASH:
        logger.warning("that account is using the built-in development password.")


async def verify_login(
    session: AsyncSession, username: str, password: str
) -> Optional[User]:
    user = await users.get_by_username(session, username)
    if user is None:
        pwd_context.verify(password, _DUMMY_HASH)
        return None
    if not user.is_active:
        # Still hash, so a disabled account is not distinguishable by timing.
        pwd_context.verify(password, _DUMMY_HASH)
        logger.info("sign-in refused for disabled account %r", username)
        return None
    try:
        if pwd_context.verify(password, user.password_hash):
            return user
    except ValueError:
        logger.error("stored hash for %r is not a valid bcrypt hash", username)
    return None


# --------------------------------------------------------------------------
# Browser session
# --------------------------------------------------------------------------

def create_session_token(username: str, role: str) -> str:
    now = datetime.now(timezone.utc)
    return jwt.encode(
        {
            "sub": username,
            "role": role,
            "iat": now,
            "exp": now + timedelta(seconds=settings.session_ttl),
        },
        settings.session_secret,
        algorithm=ALGORITHM,
    )


def read_session(token: Optional[str]) -> Optional[Dict[str, str]]:
    """Return {"username", "role"} for a valid session, else None."""
    if not token or not settings.session_secret:
        return None
    try:
        payload = jwt.decode(token, settings.session_secret, algorithms=[ALGORITHM])
    except JWTError:
        return None
    username = payload.get("sub")
    if not username:
        return None
    # Sessions minted before roles existed default to the lower privilege.
    return {"username": username, "role": payload.get("role") or ROLE_OPERATOR}


# --------------------------------------------------------------------------
# Grants handed to the relay
# --------------------------------------------------------------------------

def sign_grant(username: str, device_id: str, scope: str) -> str:
    """Authorise one WebSocket upgrade, to one device, for one purpose.

    Deliberately tiny and short-lived: it travels in a query string, where it may
    well be written to an access log. The ``jti`` lets the relay burn it after a
    single use so a logged copy is worthless.
    """
    if scope not in VALID_SCOPES:
        raise ValueError(f"scope inválido: {scope}")

    now = datetime.now(timezone.utc)
    return jwt.encode(
        {
            "sub": username,
            "dev": device_id,
            "scp": scope,
            "jti": secrets.token_urlsafe(16),
            "iat": now,
            "exp": now + timedelta(seconds=settings.grant_ttl),
        },
        settings.relay_secret,
        algorithm=ALGORITHM,
    )
